package net.megalogaminguk.megalosmod.datagen;

import net.megalogaminguk.megalosmod.MegalosMod;
import net.megalogaminguk.megalosmod.block.ModBlocks;
import net.megalogaminguk.megalosmod.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, MegalosMod.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                //ORE
                .add(ModBlocks.ALUMINIUM_ORE.get())
                .add(ModBlocks.CALCIUM_ORE.get())
                .add(ModBlocks.CINNABAR_ORE.get())
                .add(ModBlocks.LEAD_ORE.get())
                .add(ModBlocks.MAGNESIUM_ORE.get())
                .add(ModBlocks.NICKEL_ORE.get())
                .add(ModBlocks.OSMIUM_ORE.get())
                .add(ModBlocks.PLATINUM_ORE.get())
                .add(ModBlocks.SILICON_ORE.get())
                .add(ModBlocks.SILVER_ORE.get())
                .add(ModBlocks.SODIUM_ORE.get())
                .add(ModBlocks.TIN_ORE.get())
                .add(ModBlocks.TITANIUM_ORE.get())
                .add(ModBlocks.ZINC_ORE.get())
                .add(ModBlocks.ZIRCONIUM_ORE.get())
                .add(ModBlocks.ANTIMONY_ORE.get())
                .add(ModBlocks.BISMUTH_ORE.get())
                .add(ModBlocks.CADMIUM_ORE.get())
                .add(ModBlocks.CHROMIUM_ORE.get())
                .add(ModBlocks.COBALT_ORE.get())
                .add(ModBlocks.GALLIUM_ORE.get())
                .add(ModBlocks.IRIDIUM_ORE.get())
                .add(ModBlocks.MANGANESE_ORE.get())
                .add(ModBlocks.MOLYBDENUM_ORE.get())
                .add(ModBlocks.PALLADIUM_ORE.get())
                .add(ModBlocks.POTASSIUM_ORE.get())
                .add(ModBlocks.RUTHENIUM_ORE.get())
                .add(ModBlocks.THALLIUM_ORE.get())
                .add(ModBlocks.TUNGSTEN_ORE.get())
                .add(ModBlocks.ARSENIC_ORE.get())
                .add(ModBlocks.BARIUM_ORE.get())
                .add(ModBlocks.BERYLLIUM_ORE.get())
                .add(ModBlocks.CAESIUM_ORE.get())
                .add(ModBlocks.GERMANIUM_ORE.get())
                .add(ModBlocks.HAFNIUM_ORE.get())
                .add(ModBlocks.INDIUM_ORE.get())
                .add(ModBlocks.NIOBIUM_ORE.get())
                .add(ModBlocks.PHOSPHORUS_ORE.get())
                .add(ModBlocks.RHENIUM_ORE.get())
                .add(ModBlocks.RHODIUM_ORE.get())
                .add(ModBlocks.SELENIUM_ORE.get())
                .add(ModBlocks.TECHNETIUM_ORE.get())
                .add(ModBlocks.TELLURIUM_ORE.get())
                .add(ModBlocks.LITHIUM_ORE.get())
                .add(ModBlocks.RUBIDIUM_ORE.get())
                .add(ModBlocks.SCANDIUM_ORE.get())
                .add(ModBlocks.STRONTIUM_ORE.get())
                .add(ModBlocks.TANTALUM_ORE.get())
                .add(ModBlocks.VANADIUM_ORE.get())
                .add(ModBlocks.YTTRIUM_ORE.get())

                //Blocks
                .add(ModBlocks.ALUMINIUM_BLOCK.get())
                .add(ModBlocks.ANTIMONY_BLOCK.get())
                .add(ModBlocks.ARSENIC_BLOCK.get())
                .add(ModBlocks.BARIUM_BLOCK.get())
                .add(ModBlocks.BERYLLIUM_BLOCK.get())
                .add(ModBlocks.BISMUTH_BLOCK.get())
                .add(ModBlocks.CADMIUM_BLOCK.get())
                .add(ModBlocks.CAESIUM_BLOCK.get())
                .add(ModBlocks.CALCIUM_BLOCK.get())
                .add(ModBlocks.CHROMIUM_BLOCK.get())
                .add(ModBlocks.COBALT_BLOCK.get())
                .add(ModBlocks.GALLIUM_BLOCK.get())
                .add(ModBlocks.GERMANIUM_BLOCK.get())
                .add(ModBlocks.HAFNIUM_BLOCK.get())
                .add(ModBlocks.INDIUM_BLOCK.get())
                .add(ModBlocks.IRIDIUM_BLOCK.get())
                .add(ModBlocks.LEAD_BLOCK.get())
                .add(ModBlocks.LITHIUM_BLOCK.get())
                .add(ModBlocks.MAGNESIUM_BLOCK.get())
                .add(ModBlocks.MANGANESE_BLOCK.get())
                .add(ModBlocks.MOLYBDENUM_BLOCK.get())
                .add(ModBlocks.NICKEL_BLOCK.get())
                .add(ModBlocks.NIOBIUM_BLOCK.get())
                .add(ModBlocks.OSMIUM_BLOCK.get())
                .add(ModBlocks.PALLADIUM_BLOCK.get())
                .add(ModBlocks.PHOSPHORUS_BLOCK.get())
                .add(ModBlocks.PLATINUM_BLOCK.get())
                .add(ModBlocks.POTASSIUM_BLOCK.get())
                .add(ModBlocks.RHENIUM_BLOCK.get())
                .add(ModBlocks.RHODIUM_BLOCK.get())
                .add(ModBlocks.RUBIDIUM_BLOCK.get())
                .add(ModBlocks.RUTHENIUM_BLOCK.get())
                .add(ModBlocks.SCANDIUM_BLOCK.get())
                .add(ModBlocks.SELENIUM_BLOCK.get())
                .add(ModBlocks.SILICON_BLOCK.get())
                .add(ModBlocks.SILVER_BLOCK.get())
                .add(ModBlocks.SODIUM_BLOCK.get())
                .add(ModBlocks.STRONTIUM_BLOCK.get())
                .add(ModBlocks.TANTALUM_BLOCK.get())
                .add(ModBlocks.TECHNETIUM_BLOCK.get())
                .add(ModBlocks.TELLURIUM_BLOCK.get())
                .add(ModBlocks.THALLIUM_BLOCK.get())
                .add(ModBlocks.TIN_BLOCK.get())
                .add(ModBlocks.TITANIUM_BLOCK.get())
                .add(ModBlocks.TUNGSTEN_BLOCK.get())
                .add(ModBlocks.VANADIUM_BLOCK.get())
                .add(ModBlocks.YTTRIUM_BLOCK.get())
                .add(ModBlocks.ZINC_BLOCK.get())
                .add(ModBlocks.ZIRCONIUM_BLOCK.get())

                //Raw Blocks
                .add(ModBlocks.RAW_ALUMINIUM_BLOCK.get())
                .add(ModBlocks.RAW_ANTIMONY_BLOCK.get())
                .add(ModBlocks.RAW_ARSENIC_BLOCK.get())
                .add(ModBlocks.RAW_BARIUM_BLOCK.get())
                .add(ModBlocks.RAW_BERYLLIUM_BLOCK.get())
                .add(ModBlocks.RAW_BISMUTH_BLOCK.get())
                .add(ModBlocks.RAW_CADMIUM_BLOCK.get())
                .add(ModBlocks.RAW_CAESIUM_BLOCK.get())
                .add(ModBlocks.RAW_CALCIUM_BLOCK.get())
                .add(ModBlocks.RAW_CHROMIUM_BLOCK.get())
                .add(ModBlocks.RAW_COBALT_BLOCK.get())
                .add(ModBlocks.RAW_GALLIUM_BLOCK.get())
                .add(ModBlocks.RAW_GERMANIUM_BLOCK.get())
                .add(ModBlocks.RAW_HAFNIUM_BLOCK.get())
                .add(ModBlocks.RAW_INDIUM_BLOCK.get())
                .add(ModBlocks.RAW_IRIDIUM_BLOCK.get())
                .add(ModBlocks.RAW_LEAD_BLOCK.get())
                .add(ModBlocks.RAW_LITHIUM_BLOCK.get())
                .add(ModBlocks.RAW_MAGNESIUM_BLOCK.get())
                .add(ModBlocks.RAW_MANGANESE_BLOCK.get())
                .add(ModBlocks.RAW_MOLYBDENUM_BLOCK.get())
                .add(ModBlocks.RAW_NICKEL_BLOCK.get())
                .add(ModBlocks.RAW_NIOBIUM_BLOCK.get())
                .add(ModBlocks.RAW_OSMIUM_BLOCK.get())
                .add(ModBlocks.RAW_PALLADIUM_BLOCK.get())
                .add(ModBlocks.RAW_PHOSPHORUS_BLOCK.get())
                .add(ModBlocks.RAW_PLATINUM_BLOCK.get())
                .add(ModBlocks.RAW_POTASSIUM_BLOCK.get())
                .add(ModBlocks.RAW_RHENIUM_BLOCK.get())
                .add(ModBlocks.RAW_RHODIUM_BLOCK.get())
                .add(ModBlocks.RAW_RUBIDIUM_BLOCK.get())
                .add(ModBlocks.RAW_RUTHENIUM_BLOCK.get())
                .add(ModBlocks.RAW_SCANDIUM_BLOCK.get())
                .add(ModBlocks.RAW_SELENIUM_BLOCK.get())
                .add(ModBlocks.RAW_SILICON_BLOCK.get())
                .add(ModBlocks.RAW_SILVER_BLOCK.get())
                .add(ModBlocks.RAW_SODIUM_BLOCK.get())
                .add(ModBlocks.RAW_STRONTIUM_BLOCK.get())
                .add(ModBlocks.RAW_TANTALUM_BLOCK.get())
                .add(ModBlocks.RAW_TECHNETIUM_BLOCK.get())
                .add(ModBlocks.RAW_TELLURIUM_BLOCK.get())
                .add(ModBlocks.RAW_THALLIUM_BLOCK.get())
                .add(ModBlocks.RAW_TIN_BLOCK.get())
                .add(ModBlocks.RAW_TITANIUM_BLOCK.get())
                .add(ModBlocks.RAW_TUNGSTEN_BLOCK.get())
                .add(ModBlocks.RAW_VANADIUM_BLOCK.get())
                .add(ModBlocks.RAW_YTTRIUM_BLOCK.get())
                .add(ModBlocks.RAW_ZINC_BLOCK.get())
                .add(ModBlocks.RAW_ZIRCONIUM_BLOCK.get());

        tag(BlockTags.NEEDS_STONE_TOOL)
                .add(ModBlocks.ALUMINIUM_ORE.get())
                .add(ModBlocks.CALCIUM_ORE.get())
                .add(ModBlocks.CINNABAR_ORE.get())
                .add(ModBlocks.LEAD_ORE.get())
                .add(ModBlocks.MAGNESIUM_ORE.get())
                .add(ModBlocks.NICKEL_ORE.get())
                .add(ModBlocks.OSMIUM_ORE.get())
                .add(ModBlocks.PLATINUM_ORE.get())
                .add(ModBlocks.SILICON_ORE.get())
                .add(ModBlocks.SILVER_ORE.get())
                .add(ModBlocks.SODIUM_ORE.get())
                .add(ModBlocks.TIN_ORE.get())
                .add(ModBlocks.TITANIUM_ORE.get())
                .add(ModBlocks.ZINC_ORE.get())
                .add(ModBlocks.ZIRCONIUM_ORE.get());

        tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.ALUMINIUM_BLOCK.get())
                .add(ModBlocks.ANTIMONY_BLOCK.get())
                .add(ModBlocks.ARSENIC_BLOCK.get())
                .add(ModBlocks.BARIUM_BLOCK.get())
                .add(ModBlocks.BERYLLIUM_BLOCK.get())
                .add(ModBlocks.BISMUTH_BLOCK.get())
                .add(ModBlocks.CADMIUM_BLOCK.get())
                .add(ModBlocks.CAESIUM_BLOCK.get())
                .add(ModBlocks.CALCIUM_BLOCK.get())
                .add(ModBlocks.CHROMIUM_BLOCK.get())
                .add(ModBlocks.COBALT_BLOCK.get())
                .add(ModBlocks.GALLIUM_BLOCK.get())
                .add(ModBlocks.GERMANIUM_BLOCK.get())
                .add(ModBlocks.HAFNIUM_BLOCK.get())
                .add(ModBlocks.INDIUM_BLOCK.get())
                .add(ModBlocks.IRIDIUM_BLOCK.get())
                .add(ModBlocks.LEAD_BLOCK.get())
                .add(ModBlocks.LITHIUM_BLOCK.get())
                .add(ModBlocks.MAGNESIUM_BLOCK.get())
                .add(ModBlocks.MANGANESE_BLOCK.get())
                .add(ModBlocks.MOLYBDENUM_BLOCK.get())
                .add(ModBlocks.NICKEL_BLOCK.get())
                .add(ModBlocks.NIOBIUM_BLOCK.get())
                .add(ModBlocks.OSMIUM_BLOCK.get())
                .add(ModBlocks.PALLADIUM_BLOCK.get())
                .add(ModBlocks.PHOSPHORUS_BLOCK.get())
                .add(ModBlocks.PLATINUM_BLOCK.get())
                .add(ModBlocks.POTASSIUM_BLOCK.get())
                .add(ModBlocks.RHENIUM_BLOCK.get())
                .add(ModBlocks.RHODIUM_BLOCK.get())
                .add(ModBlocks.RUBIDIUM_BLOCK.get())
                .add(ModBlocks.RUTHENIUM_BLOCK.get())
                .add(ModBlocks.SCANDIUM_BLOCK.get())
                .add(ModBlocks.SELENIUM_BLOCK.get())
                .add(ModBlocks.SILICON_BLOCK.get())
                .add(ModBlocks.SILVER_BLOCK.get())
                .add(ModBlocks.SODIUM_BLOCK.get())
                .add(ModBlocks.STRONTIUM_BLOCK.get())
                .add(ModBlocks.TANTALUM_BLOCK.get())
                .add(ModBlocks.TECHNETIUM_BLOCK.get())
                .add(ModBlocks.TELLURIUM_BLOCK.get())
                .add(ModBlocks.THALLIUM_BLOCK.get())
                .add(ModBlocks.TIN_BLOCK.get())
                .add(ModBlocks.TITANIUM_BLOCK.get())
                .add(ModBlocks.TUNGSTEN_BLOCK.get())
                .add(ModBlocks.VANADIUM_BLOCK.get())
                .add(ModBlocks.YTTRIUM_BLOCK.get())
                .add(ModBlocks.ZINC_BLOCK.get())
                .add(ModBlocks.ZIRCONIUM_BLOCK.get())

                //Raw
                .add(ModBlocks.RAW_ALUMINIUM_BLOCK.get())
                .add(ModBlocks.RAW_ANTIMONY_BLOCK.get())
                .add(ModBlocks.RAW_ARSENIC_BLOCK.get())
                .add(ModBlocks.RAW_BARIUM_BLOCK.get())
                .add(ModBlocks.RAW_BERYLLIUM_BLOCK.get())
                .add(ModBlocks.RAW_BISMUTH_BLOCK.get())
                .add(ModBlocks.RAW_CADMIUM_BLOCK.get())
                .add(ModBlocks.RAW_CAESIUM_BLOCK.get())
                .add(ModBlocks.RAW_CALCIUM_BLOCK.get())
                .add(ModBlocks.RAW_CHROMIUM_BLOCK.get())
                .add(ModBlocks.RAW_COBALT_BLOCK.get())
                .add(ModBlocks.RAW_GALLIUM_BLOCK.get())
                .add(ModBlocks.RAW_GERMANIUM_BLOCK.get())
                .add(ModBlocks.RAW_HAFNIUM_BLOCK.get())
                .add(ModBlocks.RAW_INDIUM_BLOCK.get())
                .add(ModBlocks.RAW_IRIDIUM_BLOCK.get())
                .add(ModBlocks.RAW_LEAD_BLOCK.get())
                .add(ModBlocks.RAW_LITHIUM_BLOCK.get())
                .add(ModBlocks.RAW_MAGNESIUM_BLOCK.get())
                .add(ModBlocks.RAW_MANGANESE_BLOCK.get())
                .add(ModBlocks.RAW_MOLYBDENUM_BLOCK.get())
                .add(ModBlocks.RAW_NICKEL_BLOCK.get())
                .add(ModBlocks.RAW_NIOBIUM_BLOCK.get())
                .add(ModBlocks.RAW_OSMIUM_BLOCK.get())
                .add(ModBlocks.RAW_PALLADIUM_BLOCK.get())
                .add(ModBlocks.RAW_PHOSPHORUS_BLOCK.get())
                .add(ModBlocks.RAW_PLATINUM_BLOCK.get())
                .add(ModBlocks.RAW_POTASSIUM_BLOCK.get())
                .add(ModBlocks.RAW_RHENIUM_BLOCK.get())
                .add(ModBlocks.RAW_RHODIUM_BLOCK.get())
                .add(ModBlocks.RAW_RUBIDIUM_BLOCK.get())
                .add(ModBlocks.RAW_RUTHENIUM_BLOCK.get())
                .add(ModBlocks.RAW_SCANDIUM_BLOCK.get())
                .add(ModBlocks.RAW_SELENIUM_BLOCK.get())
                .add(ModBlocks.RAW_SILICON_BLOCK.get())
                .add(ModBlocks.RAW_SILVER_BLOCK.get())
                .add(ModBlocks.RAW_SODIUM_BLOCK.get())
                .add(ModBlocks.RAW_STRONTIUM_BLOCK.get())
                .add(ModBlocks.RAW_TANTALUM_BLOCK.get())
                .add(ModBlocks.RAW_TECHNETIUM_BLOCK.get())
                .add(ModBlocks.RAW_TELLURIUM_BLOCK.get())
                .add(ModBlocks.RAW_THALLIUM_BLOCK.get())
                .add(ModBlocks.RAW_TIN_BLOCK.get())
                .add(ModBlocks.RAW_TITANIUM_BLOCK.get())
                .add(ModBlocks.RAW_TUNGSTEN_BLOCK.get())
                .add(ModBlocks.RAW_VANADIUM_BLOCK.get())
                .add(ModBlocks.RAW_YTTRIUM_BLOCK.get())
                .add(ModBlocks.RAW_ZINC_BLOCK.get())
                .add(ModBlocks.RAW_ZIRCONIUM_BLOCK.get())

        //Alloys - Aluminium
        .add(ModBlocks.AA_BLOCK.get())
        .add(ModBlocks.AL_LI_BLOCK.get())
        .add(ModBlocks.ALNICO_BLOCK.get())
        .add(ModBlocks.ALUMINIUM_SCANDIUM_BLOCK.get())
        .add(ModBlocks.BIRMABRIGHT_BLOCK.get())
        .add(ModBlocks.DEVARDA_BLOCK.get())
        .add(ModBlocks.DURALUMIN_BLOCK.get())
        .add(ModBlocks.HIDUMINIUM_BLOCK.get())
        .add(ModBlocks.HYDRONALIUM_BLOCK.get())
        .add(ModBlocks.ITALMA_BLOCK.get())
        .add(ModBlocks.MAGNALIUM_BLOCK.get())
        .add(ModBlocks.MAGNOX_BLOCK.get())
        .add(ModBlocks.NAMBE_BLOCK.get())
        .add(ModBlocks.NITIAL_BLOCK.get())
        .add(ModBlocks.SILUMIN_BLOCK.get())
        .add(ModBlocks.Y_ALLOY_BLOCK.get())
        .add(ModBlocks.ZAMAK_BLOCK.get())

        //Beryllium
        .add(ModBlocks.LOCKALLOY_BLOCK.get())

        //Bismuth
        .add(ModBlocks.BISMANOL_BLOCK.get())
        .add(ModBlocks.CERROBEND_BLOCK.get())
        .add(ModBlocks.CERROSAFE_BLOCK.get())
        .add(ModBlocks.FIELDS_METAL_BLOCK.get())
        .add(ModBlocks.ROSE_METAL_BLOCK.get())
        .add(ModBlocks.WOODS_METAL_BLOCK.get())

        //Chromium
        .add(ModBlocks.CHROMIUM_HYDRIDE_BLOCK.get())
        .add(ModBlocks.CRNISZWTI_BLOCK.get())
        .add(ModBlocks.NICHROME_BLOCK.get())

        //Cobalt
        .add(ModBlocks.ELGILOY_BLOCK.get())
        .add(ModBlocks.MEGALLIUM_BLOCK.get())
        .add(ModBlocks.STELLITE_BLOCK.get())
        .add(ModBlocks.TALONITE_BLOCK.get())
        .add(ModBlocks.ULTIMET_BLOCK.get())
        .add(ModBlocks.VITALLIUM_BLOCK.get())

        //Copper
        .add(ModBlocks.ALUMINIUM_BRONZE_BLOCK.get())
        .add(ModBlocks.ARSENICAL_COPPER_BLOCK.get())
        .add(ModBlocks.BELL_METAL_BLOCK.get())
        .add(ModBlocks.BERYLLIUM_COPPER_BLOCK.get())
        .add(ModBlocks.BILLON_BLOCK.get())
        .add(ModBlocks.BRASS_BLOCK.get())
        .add(ModBlocks.BRONZE_BLOCK.get())
        .add(ModBlocks.CALAMINE_BRASS_BLOCK.get())
        .add(ModBlocks.CHINESE_SILVER_BLOCK.get())
        .add(ModBlocks.CONSTANTAN_BLOCK.get())
        .add(ModBlocks.COPPER_HYDRIDE_BLOCK.get())
        .add(ModBlocks.COPPER_TUNGSTEN_BLOCK.get())
        .add(ModBlocks.CORINTHIAN_BRONZE_BLOCK.get())
        .add(ModBlocks.CUNIFE_BLOCK.get())
        .add(ModBlocks.CUAG_BLOCK.get())
        .add(ModBlocks.CYMBAL_ALLOY_BLOCK.get())
        .add(ModBlocks.DUTCH_METAL_BLOCK.get())
        .add(ModBlocks.FLORENTINE_BRONZE_BLOCK.get())
        .add(ModBlocks.GILDING_METAL_BLOCK.get())
        .add(ModBlocks.GLUCYDUR_BLOCK.get())
        .add(ModBlocks.GUANIN_BLOCK.get())
        .add(ModBlocks.GUN_METAL_BLOCK.get())
        .add(ModBlocks.HEPATIZON_BLOCK.get())
        .add(ModBlocks.MANGANIN_BLOCK.get())
        .add(ModBlocks.MELCHIOR_BLOCK.get())
        .add(ModBlocks.MUNTZ_METAL_BLOCK.get())
        .add(ModBlocks.NICKEL_SILVER_BLOCK.get())
        .add(ModBlocks.NORDIC_GOLD_BLOCK.get())
        .add(ModBlocks.ORMOLU_BLOCK.get())
        .add(ModBlocks.PHOSPHOR_BRONZE_BLOCK.get())
        .add(ModBlocks.PINCHBECK_BLOCK.get())
        .add(ModBlocks.PRINCES_METAL_BLOCK.get())
        .add(ModBlocks.SHAKUDO_BLOCK.get())
        .add(ModBlocks.SILICON_BRONZE_BLOCK.get())
        .add(ModBlocks.SPECULUM_METAL_BLOCK.get())
        .add(ModBlocks.TOMBAC_BLOCK.get())
        .add(ModBlocks.TUMBAGA_BLOCK.get())
        .add(ModBlocks.WHITE_BRONZE_BLOCK.get())

        //Gallium
        .add(ModBlocks.AL_GA_BLOCK.get())
        .add(ModBlocks.GALFENOL_BLOCK.get())
        .add(ModBlocks.GALINSTAN_BLOCK.get())

        //Gold
        .add(ModBlocks.COLORED_GOLD_BLOCK.get())
        .add(ModBlocks.CROWN_GOLD_BLOCK.get())
        .add(ModBlocks.ELECTRUM_BLOCK.get())
        .add(ModBlocks.RHODITE_BLOCK.get())
        .add(ModBlocks.ROSE_GOLD_BLOCK.get())
        .add(ModBlocks.WHITE_GOLD_BLOCK.get())

        //Iron
        .add(ModBlocks.ANTHRACITE_IRON_BLOCK.get())
        .add(ModBlocks.BULAT_STEEL_BLOCK.get())
        .add(ModBlocks.CAST_IRON_BLOCK.get())
        .add(ModBlocks.CHROMOLY_BLOCK.get())
        .add(ModBlocks.CRUCIBLE_STEEL_BLOCK.get())
        .add(ModBlocks.DAMASCUS_STEEL_BLOCK.get())
        .add(ModBlocks.DUCOL_BLOCK.get())
        .add(ModBlocks.ELINVAR_BLOCK.get())
        .add(ModBlocks.FERNICO_BLOCK.get())
        .add(ModBlocks.FERROCHROMIUM_BLOCK.get())
        .add(ModBlocks.FERROMAGNESIUM_BLOCK.get())
        .add(ModBlocks.FERROMANGANESE_BLOCK.get())
        .add(ModBlocks.FERROMOLYBDENUM_BLOCK.get())
        .add(ModBlocks.FERRONICKEL_BLOCK.get())
        .add(ModBlocks.FERROPHOSPHORUS_BLOCK.get())
        .add(ModBlocks.FERROSILICON_BLOCK.get())
        .add(ModBlocks.FERROTITANIUM_BLOCK.get())
        .add(ModBlocks.FERROVANADIUM_BLOCK.get())
        .add(ModBlocks.HIGHSPEED_STEEL_BLOCK.get())
        .add(ModBlocks.HSLA_STEEL_BLOCK.get())
        .add(ModBlocks.INVAR_BLOCK.get())
        .add(ModBlocks.IRON_HYDRIDE_BLOCK.get())
        .add(ModBlocks.KANTHAL_BLOCK.get())
        .add(ModBlocks.KOVAR_BLOCK.get())
        .add(ModBlocks.MARAGING_STEEL_BLOCK.get())
        .add(ModBlocks.MUSHET_STEEL_BLOCK.get())
        .add(ModBlocks.PIG_IRON_BLOCK.get())
        .add(ModBlocks.REYNOLDS_FTO_BLOCK.get())
        .add(ModBlocks.SILICON_STEEL_BLOCK.get())
        .add(ModBlocks.SILVER_STEEL_BLOCK.get())
        .add(ModBlocks.SPIEGELEISEN_BLOCK.get())
        .add(ModBlocks.SPRING_STEEL_BLOCK.get())
        .add(ModBlocks.STAINLESS_STEEL_BLOCK.get())
        .add(ModBlocks.STABALLOY_BLOCK.get())
        .add(ModBlocks.STEEL_BLOCK.get())
        .add(ModBlocks.TOOL_STEEL_BLOCK.get())
        .add(ModBlocks.WEATHERING_STEEL_BLOCK.get())
        .add(ModBlocks.WOOTZ_STEEL_BLOCK.get())
        .add(ModBlocks.WROUGHT_IRON_BLOCK.get())

        //Lead
        .add(ModBlocks.MOLYBDOCHALKOS_BLOCK.get())
        .add(ModBlocks.SOLDER_BLOCK.get())
        .add(ModBlocks.TERNE_BLOCK.get())
        .add(ModBlocks.TYPE_METAL_BLOCK.get())

        //Magnesium
        .add(ModBlocks.ELEKTRON_BLOCK.get())
        .add(ModBlocks.TMGALZN_BLOCK.get())

        //Manganese
        .add(ModBlocks.MNFZ_BLOCK.get())
        .add(ModBlocks.MNSZ_BLOCK.get())

        //Mercury
        .add(ModBlocks.ZINC_AMALGAM_BLOCK.get())
        .add(ModBlocks.ASHTADHATU_BLOCK.get())

        //Nickel
        .add(ModBlocks.ALUMEL_BLOCK.get())
        .add(ModBlocks.BRIGHTRAY_BLOCK.get())
        .add(ModBlocks.CHROMEL_BLOCK.get())
        .add(ModBlocks.COIN_SILVER_BLOCK.get())
        .add(ModBlocks.COPPER_NICKEL_BLOCK.get())
        .add(ModBlocks.CUPRONICKEL_BLOCK.get())
        .add(ModBlocks.GERMAN_SILVER_BLOCK.get())
        .add(ModBlocks.HASTELLOY_BLOCK.get())
        .add(ModBlocks.HAUSLER_BLOCK.get())
        .add(ModBlocks.INCONEL_BLOCK.get())
        .add(ModBlocks.INCONEL_SES_BLOCK.get())
        .add(ModBlocks.MONEL_METAL_BLOCK.get())
        .add(ModBlocks.MU_METAL_BLOCK.get())
        .add(ModBlocks.NICKEL_CARBON_BLOCK.get())
        .add(ModBlocks.NICKEL_HYDRIDE_BLOCK.get())
        .add(ModBlocks.NICROSIL_BLOCK.get())
        .add(ModBlocks.NIMONIC_BLOCK.get())
        .add(ModBlocks.NISIL_BLOCK.get())
        .add(ModBlocks.NITINOL_BLOCK.get())
        .add(ModBlocks.PERMALLOY_BLOCK.get())
        .add(ModBlocks.SUPERMALLOY_BLOCK.get())

        //Potassium
        .add(ModBlocks.KLI_BLOCK.get())
        .add(ModBlocks.NAK_BLOCK.get())

        //Rhodium
        .add(ModBlocks.PSEUDO_PALLADIUM_BLOCK.get())

        //Scandium
        .add(ModBlocks.SCANDIUM_HYDRIDE_BLOCK.get())

        //Silver
        .add(ModBlocks.ARGENTIUM_STERLING_SILVER_BLOCK.get())
        .add(ModBlocks.BRITANNIA_SILVER_BLOCK.get())
        .add(ModBlocks.DORE_BLOCK.get())
        .add(ModBlocks.DYMALLOY_BLOCK.get())
        .add(ModBlocks.GOLOID_BLOCK.get())
        .add(ModBlocks.PLATINUM_SILVER_BLOCK.get())
        .add(ModBlocks.SHIBUICHI_BLOCK.get())
        .add(ModBlocks.STERLING_SILVER_BLOCK.get())
        .add(ModBlocks.TIBETAN_SILVER_BLOCK.get())

        //Tin
        .add(ModBlocks.BABBITT_BLOCK.get())
        .add(ModBlocks.BRITANNIUM_BLOCK.get())
        .add(ModBlocks.PEWTER_BLOCK.get())
        .add(ModBlocks.QUEENS_METAL_BLOCK.get())

        //Titanium
        .add(ModBlocks.BETA_C_BLOCK.get())
        .add(ModBlocks.GUM_METAL_BLOCK.get())
        .add(ModBlocks.SAL_FV_BLOCK.get())
        .add(ModBlocks.TITANIUM_GOLD_BLOCK.get())
        .add(ModBlocks.TITANIUM_HYDRIDE_BLOCK.get())
        .add(ModBlocks.TITANIUM_NITRIDE_BLOCK.get())

        //Zirconium
        .add(ModBlocks.ZIRCALOY_BLOCK.get());

        tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(ModBlocks.ARSENIC_ORE.get())
                .add(ModBlocks.BARIUM_ORE.get())
                .add(ModBlocks.BERYLLIUM_ORE.get())
                .add(ModBlocks.CAESIUM_ORE.get())
                .add(ModBlocks.GERMANIUM_ORE.get())
                .add(ModBlocks.HAFNIUM_ORE.get())
                .add(ModBlocks.INDIUM_ORE.get())
                .add(ModBlocks.NIOBIUM_ORE.get())
                .add(ModBlocks.PHOSPHORUS_ORE.get())
                .add(ModBlocks.RHENIUM_ORE.get())
                .add(ModBlocks.RHODIUM_ORE.get())
                .add(ModBlocks.SELENIUM_ORE.get())
                .add(ModBlocks.TECHNETIUM_ORE.get())
                .add(ModBlocks.TELLURIUM_ORE.get())
                .add(ModBlocks.LITHIUM_ORE.get())
                .add(ModBlocks.RUBIDIUM_ORE.get())
                .add(ModBlocks.SCANDIUM_ORE.get())
                .add(ModBlocks.STRONTIUM_ORE.get())
                .add(ModBlocks.TANTALUM_ORE.get())
                .add(ModBlocks.VANADIUM_ORE.get())
                .add(ModBlocks.YTTRIUM_ORE.get());

        tag(ModTags.Blocks.NEEDS_ALUMINIUM_TOOL)
                .addTag(BlockTags.NEEDS_IRON_TOOL);

        tag(ModTags.Blocks.NEEDS_SILVER_TOOL)
                .addTag(BlockTags.NEEDS_STONE_TOOL);

        tag(ModTags.Blocks.NEEDS_TECHNETIUM_TOOL)
                .addTag(BlockTags.NEEDS_STONE_TOOL);

        tag(ModTags.Blocks.NEEDS_TITANIUM_TOOL)
                .addTag(BlockTags.NEEDS_DIAMOND_TOOL);

        tag(ModTags.Blocks.INCORRECT_FOR_ALUMINIUM_TOOL)
                .addTag(BlockTags.INCORRECT_FOR_IRON_TOOL)
                .remove(ModTags.Blocks.NEEDS_ALUMINIUM_TOOL);

        tag(ModTags.Blocks.INCORRECT_FOR_SILVER_TOOL)
                .addTag(BlockTags.INCORRECT_FOR_STONE_TOOL)
                .remove(ModTags.Blocks.NEEDS_ALUMINIUM_TOOL);

        tag(ModTags.Blocks.INCORRECT_FOR_TECHNETIUM_TOOL)
                .addTag(BlockTags.INCORRECT_FOR_STONE_TOOL)
                .remove(ModTags.Blocks.NEEDS_TECHNETIUM_TOOL);

        tag(ModTags.Blocks.INCORRECT_FOR_TITANIUM_TOOL)
                .addTag(BlockTags.INCORRECT_FOR_DIAMOND_TOOL)
                .remove(ModTags.Blocks.NEEDS_TITANIUM_TOOL);

        this.tag(BlockTags.LOGS_THAT_BURN)
                .add(ModBlocks.BLACK_ASH_LOG.get())
                .add(ModBlocks.BLACK_ASH_WOOD.get())
                .add(ModBlocks.STRIPPED_BLACK_ASH_LOG.get())
                .add(ModBlocks.STRIPPED_BLACK_ASH_WOOD.get())
                .add(ModBlocks.MAPLE_SVCAMORE_LOG.get())
                .add(ModBlocks.MAPLE_SYCAMORE_WOOD.get())
                .add(ModBlocks.STRIPPED_MAPLE_SYCAMORE_LOG.get())
                .add(ModBlocks.STRIPPED_MAPLE_SYCAMORE_WOOD.get());

    }
}